// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Hovhannes-Baghdasaryan/go-patient-history/ent/migrate"

	"github.com/Hovhannes-Baghdasaryan/go-patient-history/ent/patiententity"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// PatientEntity is the client for interacting with the PatientEntity builders.
	PatientEntity *PatientEntityClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.PatientEntity = NewPatientEntityClient(c.config)
}

type (
	// config is the config for the client and its builder.
	config struct {
		// driver used for executing db requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a db/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		PatientEntity: NewPatientEntityClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		PatientEntity: NewPatientEntityClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		PatientEntity.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the db connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.PatientEntity.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.PatientEntity.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *PatientEntityMutation:
		return c.PatientEntity.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// PatientEntityClient is a client for the PatientEntity schema.
type PatientEntityClient struct {
	config
}

// NewPatientEntityClient returns a client for the PatientEntity from the given config.
func NewPatientEntityClient(c config) *PatientEntityClient {
	return &PatientEntityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `patiententity.Hooks(f(g(h())))`.
func (c *PatientEntityClient) Use(hooks ...Hook) {
	c.hooks.PatientEntity = append(c.hooks.PatientEntity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `patiententity.Intercept(f(g(h())))`.
func (c *PatientEntityClient) Intercept(interceptors ...Interceptor) {
	c.inters.PatientEntity = append(c.inters.PatientEntity, interceptors...)
}

// Create returns a builder for creating a PatientEntity entity.
func (c *PatientEntityClient) Create() *PatientEntityCreate {
	mutation := newPatientEntityMutation(c.config, OpCreate)
	return &PatientEntityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PatientEntity entities.
func (c *PatientEntityClient) CreateBulk(builders ...*PatientEntityCreate) *PatientEntityCreateBulk {
	return &PatientEntityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PatientEntityClient) MapCreateBulk(slice any, setFunc func(*PatientEntityCreate, int)) *PatientEntityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PatientEntityCreateBulk{err: fmt.Errorf("calling to PatientEntityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PatientEntityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PatientEntityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PatientEntity.
func (c *PatientEntityClient) Update() *PatientEntityUpdate {
	mutation := newPatientEntityMutation(c.config, OpUpdate)
	return &PatientEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PatientEntityClient) UpdateOne(pe *PatientEntity) *PatientEntityUpdateOne {
	mutation := newPatientEntityMutation(c.config, OpUpdateOne, withPatientEntity(pe))
	return &PatientEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PatientEntityClient) UpdateOneID(id uuid.UUID) *PatientEntityUpdateOne {
	mutation := newPatientEntityMutation(c.config, OpUpdateOne, withPatientEntityID(id))
	return &PatientEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PatientEntity.
func (c *PatientEntityClient) Delete() *PatientEntityDelete {
	mutation := newPatientEntityMutation(c.config, OpDelete)
	return &PatientEntityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PatientEntityClient) DeleteOne(pe *PatientEntity) *PatientEntityDeleteOne {
	return c.DeleteOneID(pe.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PatientEntityClient) DeleteOneID(id uuid.UUID) *PatientEntityDeleteOne {
	builder := c.Delete().Where(patiententity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PatientEntityDeleteOne{builder}
}

// Query returns a query builder for PatientEntity.
func (c *PatientEntityClient) Query() *PatientEntityQuery {
	return &PatientEntityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePatientEntity},
		inters: c.Interceptors(),
	}
}

// Get returns a PatientEntity entity by its id.
func (c *PatientEntityClient) Get(ctx context.Context, id uuid.UUID) (*PatientEntity, error) {
	return c.Query().Where(patiententity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PatientEntityClient) GetX(ctx context.Context, id uuid.UUID) *PatientEntity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PatientEntityClient) Hooks() []Hook {
	return c.hooks.PatientEntity
}

// Interceptors returns the client interceptors.
func (c *PatientEntityClient) Interceptors() []Interceptor {
	return c.inters.PatientEntity
}

func (c *PatientEntityClient) mutate(ctx context.Context, m *PatientEntityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PatientEntityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PatientEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PatientEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PatientEntityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PatientEntity mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		PatientEntity []ent.Hook
	}
	inters struct {
		PatientEntity []ent.Interceptor
	}
)
