// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/Hovhannes-Baghdasaryan/go-patient-history/ent/patiententity"
	"github.com/Hovhannes-Baghdasaryan/go-patient-history/ent/predicate"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePatientEntity = "PatientEntity"
)

// PatientEntityMutation represents an operation that mutates the PatientEntity nodes in the graph.
type PatientEntityMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	name          *string
	surname       *string
	patronymic    *string
	age           *int
	addage        *int
	gender        *patiententity.Gender
	country       *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*PatientEntity, error)
	predicates    []predicate.PatientEntity
}

var _ ent.Mutation = (*PatientEntityMutation)(nil)

// patiententityOption allows management of the mutation config using functional options.
type patiententityOption func(*PatientEntityMutation)

// newPatientEntityMutation creates new mutation for the PatientEntity entity.
func newPatientEntityMutation(c config, op Op, opts ...patiententityOption) *PatientEntityMutation {
	m := &PatientEntityMutation{
		config:        c,
		op:            op,
		typ:           TypePatientEntity,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPatientEntityID sets the ID field of the mutation.
func withPatientEntityID(id uuid.UUID) patiententityOption {
	return func(m *PatientEntityMutation) {
		var (
			err   error
			once  sync.Once
			value *PatientEntity
		)
		m.oldValue = func(ctx context.Context) (*PatientEntity, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PatientEntity.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPatientEntity sets the old PatientEntity of the mutation.
func withPatientEntity(node *PatientEntity) patiententityOption {
	return func(m *PatientEntityMutation) {
		m.oldValue = func(context.Context) (*PatientEntity, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PatientEntityMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PatientEntityMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PatientEntity entities.
func (m *PatientEntityMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the db.
func (m *PatientEntityMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the db and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PatientEntityMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PatientEntity.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *PatientEntityMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *PatientEntityMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the PatientEntity entity.
// If the PatientEntity object wasn't provided to the builder, the object is fetched from the db.
// An error is returned if the mutation operation is not UpdateOne, or the db query fails.
func (m *PatientEntityMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *PatientEntityMutation) ResetName() {
	m.name = nil
}

// SetSurname sets the "surname" field.
func (m *PatientEntityMutation) SetSurname(s string) {
	m.surname = &s
}

// Surname returns the value of the "surname" field in the mutation.
func (m *PatientEntityMutation) Surname() (r string, exists bool) {
	v := m.surname
	if v == nil {
		return
	}
	return *v, true
}

// OldSurname returns the old "surname" field's value of the PatientEntity entity.
// If the PatientEntity object wasn't provided to the builder, the object is fetched from the db.
// An error is returned if the mutation operation is not UpdateOne, or the db query fails.
func (m *PatientEntityMutation) OldSurname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSurname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSurname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSurname: %w", err)
	}
	return oldValue.Surname, nil
}

// ResetSurname resets all changes to the "surname" field.
func (m *PatientEntityMutation) ResetSurname() {
	m.surname = nil
}

// SetPatronymic sets the "patronymic" field.
func (m *PatientEntityMutation) SetPatronymic(s string) {
	m.patronymic = &s
}

// Patronymic returns the value of the "patronymic" field in the mutation.
func (m *PatientEntityMutation) Patronymic() (r string, exists bool) {
	v := m.patronymic
	if v == nil {
		return
	}
	return *v, true
}

// OldPatronymic returns the old "patronymic" field's value of the PatientEntity entity.
// If the PatientEntity object wasn't provided to the builder, the object is fetched from the db.
// An error is returned if the mutation operation is not UpdateOne, or the db query fails.
func (m *PatientEntityMutation) OldPatronymic(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPatronymic is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPatronymic requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPatronymic: %w", err)
	}
	return oldValue.Patronymic, nil
}

// ResetPatronymic resets all changes to the "patronymic" field.
func (m *PatientEntityMutation) ResetPatronymic() {
	m.patronymic = nil
}

// SetAge sets the "age" field.
func (m *PatientEntityMutation) SetAge(i int) {
	m.age = &i
	m.addage = nil
}

// Age returns the value of the "age" field in the mutation.
func (m *PatientEntityMutation) Age() (r int, exists bool) {
	v := m.age
	if v == nil {
		return
	}
	return *v, true
}

// OldAge returns the old "age" field's value of the PatientEntity entity.
// If the PatientEntity object wasn't provided to the builder, the object is fetched from the db.
// An error is returned if the mutation operation is not UpdateOne, or the db query fails.
func (m *PatientEntityMutation) OldAge(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAge is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAge requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAge: %w", err)
	}
	return oldValue.Age, nil
}

// AddAge adds i to the "age" field.
func (m *PatientEntityMutation) AddAge(i int) {
	if m.addage != nil {
		*m.addage += i
	} else {
		m.addage = &i
	}
}

// AddedAge returns the value that was added to the "age" field in this mutation.
func (m *PatientEntityMutation) AddedAge() (r int, exists bool) {
	v := m.addage
	if v == nil {
		return
	}
	return *v, true
}

// ResetAge resets all changes to the "age" field.
func (m *PatientEntityMutation) ResetAge() {
	m.age = nil
	m.addage = nil
}

// SetGender sets the "gender" field.
func (m *PatientEntityMutation) SetGender(pa patiententity.Gender) {
	m.gender = &pa
}

// Gender returns the value of the "gender" field in the mutation.
func (m *PatientEntityMutation) Gender() (r patiententity.Gender, exists bool) {
	v := m.gender
	if v == nil {
		return
	}
	return *v, true
}

// OldGender returns the old "gender" field's value of the PatientEntity entity.
// If the PatientEntity object wasn't provided to the builder, the object is fetched from the db.
// An error is returned if the mutation operation is not UpdateOne, or the db query fails.
func (m *PatientEntityMutation) OldGender(ctx context.Context) (v patiententity.Gender, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGender is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGender requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGender: %w", err)
	}
	return oldValue.Gender, nil
}

// ResetGender resets all changes to the "gender" field.
func (m *PatientEntityMutation) ResetGender() {
	m.gender = nil
}

// SetCountry sets the "country" field.
func (m *PatientEntityMutation) SetCountry(s string) {
	m.country = &s
}

// Country returns the value of the "country" field in the mutation.
func (m *PatientEntityMutation) Country() (r string, exists bool) {
	v := m.country
	if v == nil {
		return
	}
	return *v, true
}

// OldCountry returns the old "country" field's value of the PatientEntity entity.
// If the PatientEntity object wasn't provided to the builder, the object is fetched from the db.
// An error is returned if the mutation operation is not UpdateOne, or the db query fails.
func (m *PatientEntityMutation) OldCountry(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCountry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCountry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCountry: %w", err)
	}
	return oldValue.Country, nil
}

// ResetCountry resets all changes to the "country" field.
func (m *PatientEntityMutation) ResetCountry() {
	m.country = nil
}

// Where appends a list predicates to the PatientEntityMutation builder.
func (m *PatientEntityMutation) Where(ps ...predicate.PatientEntity) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PatientEntityMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PatientEntityMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PatientEntity, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PatientEntityMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PatientEntityMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PatientEntity).
func (m *PatientEntityMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PatientEntityMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, patiententity.FieldName)
	}
	if m.surname != nil {
		fields = append(fields, patiententity.FieldSurname)
	}
	if m.patronymic != nil {
		fields = append(fields, patiententity.FieldPatronymic)
	}
	if m.age != nil {
		fields = append(fields, patiententity.FieldAge)
	}
	if m.gender != nil {
		fields = append(fields, patiententity.FieldGender)
	}
	if m.country != nil {
		fields = append(fields, patiententity.FieldCountry)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PatientEntityMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case patiententity.FieldName:
		return m.Name()
	case patiententity.FieldSurname:
		return m.Surname()
	case patiententity.FieldPatronymic:
		return m.Patronymic()
	case patiententity.FieldAge:
		return m.Age()
	case patiententity.FieldGender:
		return m.Gender()
	case patiententity.FieldCountry:
		return m.Country()
	}
	return nil, false
}

// OldField returns the old value of the field from the db. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// db failed.
func (m *PatientEntityMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case patiententity.FieldName:
		return m.OldName(ctx)
	case patiententity.FieldSurname:
		return m.OldSurname(ctx)
	case patiententity.FieldPatronymic:
		return m.OldPatronymic(ctx)
	case patiententity.FieldAge:
		return m.OldAge(ctx)
	case patiententity.FieldGender:
		return m.OldGender(ctx)
	case patiententity.FieldCountry:
		return m.OldCountry(ctx)
	}
	return nil, fmt.Errorf("unknown PatientEntity field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PatientEntityMutation) SetField(name string, value ent.Value) error {
	switch name {
	case patiententity.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case patiententity.FieldSurname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSurname(v)
		return nil
	case patiententity.FieldPatronymic:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPatronymic(v)
		return nil
	case patiententity.FieldAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAge(v)
		return nil
	case patiententity.FieldGender:
		v, ok := value.(patiententity.Gender)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGender(v)
		return nil
	case patiententity.FieldCountry:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCountry(v)
		return nil
	}
	return fmt.Errorf("unknown PatientEntity field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PatientEntityMutation) AddedFields() []string {
	var fields []string
	if m.addage != nil {
		fields = append(fields, patiententity.FieldAge)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PatientEntityMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case patiententity.FieldAge:
		return m.AddedAge()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PatientEntityMutation) AddField(name string, value ent.Value) error {
	switch name {
	case patiententity.FieldAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAge(v)
		return nil
	}
	return fmt.Errorf("unknown PatientEntity numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PatientEntityMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PatientEntityMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PatientEntityMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PatientEntity nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PatientEntityMutation) ResetField(name string) error {
	switch name {
	case patiententity.FieldName:
		m.ResetName()
		return nil
	case patiententity.FieldSurname:
		m.ResetSurname()
		return nil
	case patiententity.FieldPatronymic:
		m.ResetPatronymic()
		return nil
	case patiententity.FieldAge:
		m.ResetAge()
		return nil
	case patiententity.FieldGender:
		m.ResetGender()
		return nil
	case patiententity.FieldCountry:
		m.ResetCountry()
		return nil
	}
	return fmt.Errorf("unknown PatientEntity field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PatientEntityMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PatientEntityMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PatientEntityMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PatientEntityMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PatientEntityMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PatientEntityMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PatientEntityMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PatientEntity unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PatientEntityMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PatientEntity edge %s", name)
}
