// +build tools
// +build tools
// +build tools
// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Hovhannes-Baghdasaryan/go-patient-history/ent/patiententity"
	"github.com/Hovhannes-Baghdasaryan/go-patient-history/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	patiententityFields := schema.PatientEntity{}.Fields()
	_ = patiententityFields
	// patiententityDescAge is the schema descriptor for age field.
	patiententityDescAge := patiententityFields[4].Descriptor()
	// patiententity.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	patiententity.AgeValidator = func() func(int) error {
		validators := patiententityDescAge.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(age int) error {
			for _, fn := range fns {
				if err := fn(age); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// patiententityDescID is the schema descriptor for id field.
	patiententityDescID := patiententityFields[0].Descriptor()
	// patiententity.DefaultID holds the default value on creation for the id field.
	patiententity.DefaultID = patiententityDescID.Default.(func() uuid.UUID)
}
