name: Migration CI
on:
  pull_request:
    paths:
      - '*'
jobs:
  lint:
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: dev
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0
      - uses: ariga/atlas-action@v1.0.10
        with:
          dir: ent/migrate/migrations
          dev-url: postgresql://postgres:pass@localhost:5432/dev?sslmode=disable
