// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PatientEntity is the predicate function for patiententity builders.
type PatientEntity func(*sql.Selector)
